all:
  children:
    plateforme1:
      hosts:
        stg-p1-node-[01:12]:
          ansible_host: 192.168.1.[1:12]
    plateforme2:
      hosts:
        stg-p2-node-[01:12]:
          ansible_host: 192.168.2.[1:12]
    plateforme3:
      hosts:
        stg-p3-node-[01:12]:
          ansible_host: 192.168.3.[1:12]
    plateforme4:
      hosts:
        stg-p4-node-[01:12]:
          ansible_host: 192.168.4.[1:12]
